services:
  snake-mongodb:
    image: mongo:latest
    container_name: snake-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - ./mongodb/:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - snake-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_SERVER: snake-mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - snake-network

  snake-app:
    build: /app/.
    container_name: snake-app
    ports:
      - "5000:5000"
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://user:12345@snake-mongodb:27017/snake?authSource=admin
    depends_on:
      - snake-mongodb
    restart: unless-stopped
    networks:
      - snake-network

volumes:
  mongodb_data:


networks:
  snake-network:
    driver: bridge
